FROM ubuntu:24.04
RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /var/config
RUN curl -fsSL https://static.pangolin.net/get-installer.sh | bash -s -- --bin-only
VOLUME /var/config
EXPOSE 51820/udp
# Connects to the RK-AD-Pangolin app internally
CMD ["gerbil", \
     "--reachableAt=http://gerbil:3004", \
     "--generateAndSaveKeyTo=/var/config/key", \
     "--remoteConfig=http://RK-AD-Pangolin:3001/api/v1/"]